name: inventory_system
description: "Lagos Store — Inventory Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.4
  provider: ^6.1.2
  intl: ^0.19.0
  excel: ^4.0.6
  pdf: ^3.11.1
  printing: ^5.13.1
  crypto: ^3.0.5
  path_provider: ^2.1.4
  path: ^1.9.0
  file_picker: ^8.1.6
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
